[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

# https://docs.netlify.com/routing/redirects/
[[redirects]]
  from = "/shenzhen-solitaire"
  to = "https://shenzhen-solitaire.tgratzer.com"
  status = 301

[[redirects]]
  from = "/risk-of-rain-cheatsheet"
  to = "https://risk-of-rain-cheatsheet.tgratzer.com"
  status = 301

[[redirects]]
  from = "/TechIncremental"
  to = "https://tech-incremental.tgratzer.com"
  status = 301
